name: Pull Request
description: Create a pull request to contribute to InvoiceWeMaAd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a pull request! Please ensure you've read our contributing guidelines.

  - type: input
    id: related-issue
    attributes:
      label: Related Issue
      description: Link to the issue this PR addresses
      placeholder: "#123"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of change
      multiple: true
      options:
        - Bug fix
        - New feature
        - Breaking change
        - Documentation update
        - Performance improvement
        - Code refactor
        - Test update
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of your changes
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Done
      description: Describe the tests you've added or run to verify your changes
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have tested my changes locally
          required: true
        - label: I have updated the documentation accordingly
          required: true
        - label: My changes generate no new warnings
          required: true
        - label: I have added tests that prove my fix/feature works
          required: true
        - label: All tests pass locally
          required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your changes
