import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { auth } from "@/lib/auth";
import { getBaseUrl } from "@/lib/urls";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How WeMaAd Invoice collects, uses, and protects your information.",
  alternates: { canonical: "/privacy" },
};

const LAST_UPDATED = "August 8, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold text-foreground mb-3">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-muted-foreground">{children}</div>
    </section>
  );
}

export default async function PrivacyPolicyPage() {
  const session = await auth();
  const isAuthenticated = !!session;
  const baseUrl = getBaseUrl();

  return (
    <div className="min-h-screen">
      <main className="w-full max-w-7xl mx-auto px-4 md:px-6 lg:px-8">
        <Navbar />
        <div className="max-w-3xl mx-auto py-10 md:py-16">
          <h1 className="text-3xl font-bold text-foreground mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: {LAST_UPDATED}</p>

          <Section title="1. Introduction">
            <p>
              This Privacy Policy explains how WeMaAd (&quot;WeMaAd Invoice&quot;, &quot;we&quot;,
              &quot;us&quot;) collects, uses, and shares information when you use our invoicing
              and billing software at {baseUrl.replace(/^https?:\/\//, "")} (the &quot;Service&quot;).
              By using the Service, you agree to the collection and use of information as
              described here.
            </p>
          </Section>

          <Section title="2. Information We Collect">
            <p><strong className="text-foreground">Account information.</strong> When you sign up, we collect your email address (used for passwordless sign-in) and any profile details you provide, such as your name, address, and company details (company name, email, address, tax ID, logo, and bank details you choose to display on invoices).</p>
            <p><strong className="text-foreground">Content you create.</strong> Data you enter about your clients (name, email, phone, tax ID, addresses, contact persons) and the invoices, recurring invoice schedules, and line items you create.</p>
            <p><strong className="text-foreground">Communications.</strong> Messages you send us through the contact form, and records of transactional emails the Service sends on your behalf (invoice notifications, payment reminders).</p>
            <p><strong className="text-foreground">Automatically collected information.</strong> A session cookie that keeps you signed in, and basic technical logs (IP address, timestamps) generated by our hosting and security infrastructure. We do not use third-party advertising or cross-site tracking cookies.</p>
          </Section>

          <Section title="3. How We Use Your Information">
            <ul className="list-disc pl-5 space-y-2">
              <li>To provide, operate, and maintain the Service — creating and sending invoices, tracking payment status, and running recurring billing.</li>
              <li>To authenticate you and keep your account secure.</li>
              <li>To send you transactional emails: invoice notifications, payment reminders, and account-related notices. We do not send marketing email unless you separately opt in.</li>
              <li>To respond to support or contact-form requests.</li>
              <li>To enforce plan limits and prevent abuse (e.g., rate-limiting sign-in requests).</li>
              <li>To detect, investigate, and prevent fraudulent or unauthorized activity.</li>
            </ul>
          </Section>

          <Section title="4. Data You Process About Your Clients">
            <p>
              When you add client records or generate invoices, you are the data controller
              for that information, and WeMaAd acts as a data processor storing and
              transmitting it on your behalf. You are responsible for having a lawful basis to
              collect and share your clients&apos; personal information through the Service, and
              for responding to any requests your clients make about their own data.
            </p>
          </Section>

          <Section title="5. Cookies">
            <p>
              We use a single essential session cookie to keep you signed in. This cookie is
              required for the Service to function and is not used for advertising or
              cross-site tracking. Disabling cookies in your browser will prevent you from
              staying signed in.
            </p>
          </Section>

          <Section title="6. How We Share Information">
            <p>
              We do not sell your personal information. We share information only with the
              service providers that operate the infrastructure behind WeMaAd Invoice,
              including our hosting provider, our database provider, and our transactional
              email provider — solely to the extent necessary to run the Service (for example,
              delivering the invoice emails you send through the app). We may also disclose
              information if required by law or to protect the rights, property, or safety of
              WeMaAd, our users, or others.
            </p>
          </Section>

          <Section title="7. Data Security">
            <p>
              We use industry-standard measures to protect your information, including
              encrypted connections (HTTPS), access controls, and signed links for
              share-only resources like invoice PDFs. No method of transmission or storage is
              100% secure, and we cannot guarantee absolute security.
            </p>
          </Section>

          <Section title="8. Data Retention">
            <p>
              We retain account, client, and invoice data for as long as your account is
              active, so you can continue to access your invoicing history. If you delete your
              account, we will delete or anonymize your personal information within a
              reasonable period, except where we are required to retain it for legal,
              accounting, or fraud-prevention purposes.
            </p>
          </Section>

          <Section title="9. Your Rights">
            <p>
              Depending on where you live, you may have rights to access, correct, export, or
              delete your personal information, or to object to or restrict certain
              processing. You can update most account information directly from your
              dashboard profile, or contact us using the details below to make a request.
            </p>
          </Section>

          <Section title="10. Children's Privacy">
            <p>
              The Service is intended for business use and is not directed at children. We do
              not knowingly collect personal information from anyone under 16.
            </p>
          </Section>

          <Section title="11. International Data Transfers">
            <p>
              Our infrastructure providers may process and store data in countries other than
              your own. By using the Service, you consent to your information being
              transferred to and processed in those locations.
            </p>
          </Section>

          <Section title="12. Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time. If we make material
              changes, we will update the &quot;Last updated&quot; date above and, where
              appropriate, notify you through the Service.
            </p>
          </Section>

          <Section title="13. Contact Us">
            <p>
              Questions about this Privacy Policy or your data can be sent to{" "}
              <a href="mailto:hello@wemaad.net" className="text-primary hover:underline">
                hello@wemaad.net
              </a>
              , or by mail to 3, Makram Ebeid, Nasr City, Cairo Governorate, Egypt.
            </p>
          </Section>
        </div>
      </main>
      <Footer isAuthenticated={isAuthenticated} />
    </div>
  );
}
