import { describe, it, expect, vi, afterEach } from "vitest";

vi.mock("@/lib/env", () => ({
  env: {
    AUTH_SECRET: "a".repeat(32),
    NEXT_PUBLIC_APP_URL: "https://example.com",
  },
}));

// getBaseUrl() reads process.env directly (not the validated env proxy) so
// it stays safe to call at build time without the full env schema present.
delete process.env.VERCEL_URL;
process.env.NEXT_PUBLIC_APP_URL = "https://example.com";

import { getBaseUrl, getInvoiceUrl, verifyInvoiceToken } from "../urls";

describe("getInvoiceUrl", () => {
  it("includes the invoiceId in the URL path", () => {
    const url = getInvoiceUrl("invoice-123");
    expect(url).toContain("/api/invoice/invoice-123");
  });

  it("appends a token query parameter", () => {
    const url = getInvoiceUrl("invoice-123");
    expect(url).toMatch(/\?token=[0-9a-f]+/);
  });

  it("uses NEXT_PUBLIC_APP_URL as the base", () => {
    const url = getInvoiceUrl("invoice-abc");
    expect(url).toMatch(/^https:\/\/example\.com/);
  });

  it("produces a stable URL for the same invoiceId", () => {
    expect(getInvoiceUrl("inv-1")).toBe(getInvoiceUrl("inv-1"));
  });

  it("produces different tokens for different invoiceIds", () => {
    const url1 = getInvoiceUrl("inv-1");
    const url2 = getInvoiceUrl("inv-2");
    const token1 = new URL(url1).searchParams.get("token");
    const token2 = new URL(url2).searchParams.get("token");
    expect(token1).not.toBe(token2);
  });
});

describe("verifyInvoiceToken", () => {
  it("accepts a token generated by getInvoiceUrl", () => {
    const url = getInvoiceUrl("invoice-xyz");
    const token = new URL(url).searchParams.get("token")!;
    expect(verifyInvoiceToken("invoice-xyz", token)).toBe(true);
  });

  it("rejects a token generated for a different invoiceId", () => {
    const url = getInvoiceUrl("invoice-xyz");
    const token = new URL(url).searchParams.get("token")!;
    expect(verifyInvoiceToken("invoice-OTHER", token)).toBe(false);
  });

  it("rejects a tampered token", () => {
    const url = getInvoiceUrl("invoice-xyz");
    const token = new URL(url).searchParams.get("token")!;
    const tampered = token.slice(0, -4) + "0000";
    expect(verifyInvoiceToken("invoice-xyz", tampered)).toBe(false);
  });

  it("rejects an empty string token", () => {
    expect(verifyInvoiceToken("invoice-xyz", "")).toBe(false);
  });
});

describe("getBaseUrl", () => {
  const saved = { ...process.env };
  afterEach(() => {
    process.env = { ...saved };
  });

  // Invoice emails are opened by customers without an account, possibly long
  // after sending — they must point at the stable production domain, never
  // at a per-deployment URL that can be protected or deleted.
  it("uses the stable production domain in Vercel production", () => {
    process.env.VERCEL_ENV = "production";
    process.env.VERCEL_PROJECT_PRODUCTION_URL = "invoices.example.com";
    process.env.VERCEL_URL = "invoice-wemaad-abc123.vercel.app";
    expect(getBaseUrl()).toBe("https://invoices.example.com");
    expect(getInvoiceUrl("inv-1")).toMatch(/^https:\/\/invoices\.example\.com\/api\/invoice\/inv-1\?token=/);
  });

  it("uses the deployment's own URL on previews", () => {
    process.env.VERCEL_ENV = "preview";
    process.env.VERCEL_PROJECT_PRODUCTION_URL = "invoices.example.com";
    process.env.VERCEL_URL = "invoice-wemaad-git-branch.vercel.app";
    expect(getBaseUrl()).toBe("https://invoice-wemaad-git-branch.vercel.app");
  });

  it("falls back to NEXT_PUBLIC_APP_URL off Vercel", () => {
    delete process.env.VERCEL_ENV;
    delete process.env.VERCEL_URL;
    delete process.env.VERCEL_PROJECT_PRODUCTION_URL;
    process.env.NEXT_PUBLIC_APP_URL = "http://localhost:3000/";
    expect(getBaseUrl()).toBe("http://localhost:3000");
  });
});
